checkers: ability to replace timestamp
flathub-infra/flatpak-external-data-checker pull request #297
Opened 2022-04-29 07:58 UTC by catsout

add 'timestamp' parameter to _update_version, for jsonchecker using timestamp from json rather than using the one from url response date.  

Fix for tarballs from GitHub.  

Example:
```yaml
    sources:
      - type: archive
        url: https://github.com/laurent22/joplin/archive/v2.8.4.tar.gz
        sha256: d039577ecc1e7589e7432f45d4e12308d16b5df0c1b0cc928bc451d8136761d4
        x-checker-data:
          type: json
          url: https://api.github.com/repos/laurent22/joplin/releases
          version-query: .[0] | .tag_name | sub("^v"; "")
          url-query: '"https://github.com/laurent22/joplin/archive/v" + $version +
            ".tar.gz"'
          timestamp-query: .[0] | .published_at
```

2022-04-29 08:33 UTC, wjt commented
Please could you add a test and update the documentation in README.md?

2022-04-29 15:53 UTC, gasinvein requested changes
Thanks for addressing this.
Please split changes to `checkers` and `jsonchecker` into different commits.

2022-04-29 15:53 UTC, gasinvein commented on README.md
> +`timestamp-query` is also available on non-git type sources.
I believe this is implied, and the current (pre-this-PR) behaviour is a flaw. So no need to state this explicitly.

2022-04-30 06:47 UTC, gasinvein commented on tests/test_jsonchecker.py
> +            elif data.filename == "jq-1.4.tarball_url.tar.gz":
Should match `dest-filename` in the manifest, I suppose:
```suggestion
            elif data.filename == "jq-1.4.tarball.tar.gz":
```

2022-04-30 06:49 UTC, gasinvein commented on tests/test_jsonchecker.py
> +                self.assertNotEqual(
Since we get specific release date from GH API, can we compare to it? I.e. use `assertEqual` instead of `assertNotEqual` here.

2022-04-30 07:25 UTC, gasinvein requested changes

2022-04-30 07:25 UTC, gasinvein commented on tests/test_jsonchecker.py
> +                    datetime.fromisoformat("2018-11-02T01:54:23+00:00"),
```suggestion
                    datetime.datetime.fromisoformat("2018-11-02T01:54:23+00:00"),
```

2022-04-30 07:25 UTC, gasinvein commented on tests/io.github.stedolan.jq.yml
> +          timestamp: '.published_at'
```suggestion
          timestamp-query: '.published_at'
```

2022-04-30 07:31 UTC, catsout commented
BTW, `./run-in-container.sh python3 -m unittest discover` is not work on my machine.

2022-04-30 07:33 UTC, vchernin commented
> BTW, `./run-in-container.sh python3 -m unittest discover` is not work on my machine.

https://github.com/flathub/flatpak-external-data-checker/pull/275 fixes it

2022-04-30 08:13 UTC, gasinvein approved these changes
LGTM, thanks.

2022-04-30 08:13 UTC, merged