WIP: add new Jetbrains checker
flathub-infra/flatpak-external-data-checker pull request #47
Opened 2019-12-03 14:24 UTC by Lctrs

Missing tests

2019-12-03 14:26 UTC, Lctrs commented
Kudos to @x80486 for the original code :)

2019-12-03 14:29 UTC, Lctrs commented
Ping @FakeShemp and @johanfleury. As maintainers of flatpak wrappers for some Jetbrains products, you might find some interest in this.

2019-12-04 12:49 UTC, Lctrs commented
@wjt ready for review :pray:

2019-12-05 10:48 UTC, Lctrs commented
Test result is here : https://github.com/Lctrs/flatpak-external-data-checker/commit/68ec6a40b6306b4e89eb85c1209f19e46103d963/checks?check_suite_id=343482923

2019-12-05 21:05 UTC, wjt requested changes
This is a great idea, thanks for the contribution! Just a few bits and bobs.

2019-12-05 21:05 UTC, wjt commented on src/checkers/jetbrainschecker.py
> +        assert code is not None
You can just write

```python3
code = external_data.checker_data["code"]
```

2019-12-05 21:05 UTC, wjt commented on src/checkers/jetbrainschecker.py
> +            )
```python3
release_type = external_data.checker_data.get("release-type", "release")
url = f"https://data.services.jetbrains.com/products/releases?code={code}&latest=true&type={type}"
```

2019-12-05 21:05 UTC, wjt commented on src/checkers/jetbrainschecker.py
> +        external_data.state = ExternalData.State.VALID
This is meant to refer to the state of the _current_ version, not of the new version. I think you can just drop this line.

2019-12-05 21:05 UTC, wjt commented on tests/test_jetbrainschecker.py
> +        logging.basicConfig(level=logging.DEBUG)
use init_logging() from utils (see c7f0a7cd1591a4d9b03d78f751566a7942f1935f)

2019-12-05 23:32 UTC, Lctrs commented on src/checkers/jetbrainschecker.py
> +        external_data.state = ExternalData.State.VALID
Looks like this line is needed ? :thinking:

2019-12-05 23:36 UTC, Lctrs commented on src/checkers/jetbrainschecker.py
> +            )
I'm not a Python developer (in fact, those are my first Python lines :tada:), but I read on this [blog post](https://realpython.com/python-string-formatting/) that String interpolation in Python are not safe from user input, while Template Strings are. I'm concerned that a malicious user can just get @flathubbot's token access in the log of the action for example.

2019-12-06 15:15 UTC, barthalion commented on src/checkers/jetbrainschecker.py
> +            )
Technically speaking, I can think of multiple ways a malicious user could already take and none includes string interpolation… So I wouldn't worry too much.

2019-12-06 15:19 UTC, Lctrs commented on src/checkers/jetbrainschecker.py
> +            )
Okay done.

2019-12-18 20:01 UTC, wjt approved these changes
LGTM, thanks!

2019-12-18 20:01 UTC, merged