Fix all pep8 and pyflakes failures, add helper run_tests script
flathub-infra/flatpak-external-data-checker pull request #5
Opened 2018-05-07 21:59 UTC by ahayzen

Understand if you don't want this, not everyone wants 79 char line lengths :-)

Before
```
$ pep8 .
./src/checker.py:27:1: E302 expected 2 blank lines, found 1
./src/checker.py:30:1: E302 expected 2 blank lines, found 1
./src/checker.py:37:80: E501 line too long (81 > 79 characters)
./src/checker.py:38:80: E501 line too long (82 > 79 characters)
./src/checker.py:41:80: E501 line too long (84 > 79 characters)
./src/checker.py:42:80: E501 line too long (81 > 79 characters)
./src/checker.py:43:80: E501 line too long (87 > 79 characters)
./src/checker.py:48:80: E501 line too long (82 > 79 characters)
./src/checker.py:49:80: E501 line too long (89 > 79 characters)
./src/checker.py:54:75: E502 the backslash is redundant between brackets
./src/checker.py:99:18: E201 whitespace after '{'
./src/checker.py:122:25: E703 statement ends with a semicolon
./src/lib/externaldata.py:27:1: E302 expected 2 blank lines, found 1
./src/lib/externaldata.py:40:23: E261 at least two spaces before inline comment
./src/lib/externaldata.py:41:24: E261 at least two spaces before inline comment
./src/lib/externaldata.py:70:80: E501 line too long (81 > 79 characters)
./src/lib/externaldata.py:91:1: E302 expected 2 blank lines, found 1
./src/lib/externaldata.py:96:1: E302 expected 2 blank lines, found 1
./src/lib/externaldata.py:102:80: E501 line too long (82 > 79 characters)
./src/lib/utils.py:23:1: E302 expected 2 blank lines, found 1
./src/lib/utils.py:31:1: E302 expected 2 blank lines, found 1
./src/lib/utils.py:36:1: E302 expected 2 blank lines, found 1
./src/checkers/debianrepochecker.py:45:1: E302 expected 2 blank lines, found 1
./src/checkers/debianrepochecker.py:74:80: E501 line too long (85 > 79 characters)
./src/checkers/debianrepochecker.py:76:1: E302 expected 2 blank lines, found 1
./src/checkers/debianrepochecker.py:88:80: E501 line too long (90 > 79 characters)
./src/checkers/debianrepochecker.py:158:51: E128 continuation line under-indented for visual indent
./src/checkers/debianrepochecker.py:179:1: E305 expected 2 blank lines after class or function definition, found 1
./src/checkers/rotatingurlchecker.py:37:1: E302 expected 2 blank lines, found 1
./src/checkers/rotatingurlchecker.py:46:80: E501 line too long (91 > 79 characters)
./src/checkers/rotatingurlchecker.py:69:1: E305 expected 2 blank lines after class or function definition, found 1
./src/checkers/urlchecker.py:27:1: E302 expected 2 blank lines, found 1
./src/checkers/urlchecker.py:32:9: E722 do not use bare except'
./src/checkers/urlchecker.py:37:1: E305 expected 2 blank lines after class or function definition, found 1
./tests/test_checker.py:29:1: E402 module level import not at top of file
./tests/test_checker.py:30:1: E402 module level import not at top of file
./tests/test_checker.py:32:80: E501 line too long (80 > 79 characters)
./tests/test_checker.py:39:1: E302 expected 2 blank lines, found 1
./tests/test_checker.py:42:80: E501 line too long (87 > 79 characters)
./tests/test_checker.py:45:1: E302 expected 2 blank lines, found 1
./tests/test_checker.py:87:80: E501 line too long (84 > 79 characters)
./tests/test_checker.py:90:80: E501 line too long (81 > 79 characters)
./tests/test_checker.py:96:1: E305 expected 2 blank lines after class or function definition, found 1

$ pyflakes3 .
./src/lib/externaldata.py:75: undefined name '__class__'
./src/lib/externaldata.py:76: undefined name '__class__'
```

After

```
$ pep8 .
$ pyflakes3 .
```

I also added a `run_tests.sh` script to set the PYTHONPATH instead of using the `sys` module, maybe there should be a `run_linters.sh` or something if you accept this for pep8 + pyflakes3 ?

2018-06-05 22:29 UTC, joaquimrocha commented on src/checker.py
> +        self._external_data = (
Is this expected by pep8? I really don't love this change.

2018-06-05 22:30 UTC, joaquimrocha commented on src/checker.py
> -                continue;
Oops.

2018-06-05 22:31 UTC, joaquimrocha commented on src/lib/externaldata.py
> +        info = (
Again, I don't love this change.

2018-06-05 22:34 UTC, joaquimrocha commented on src/lib/externaldata.py
> +        json_data['type'] = self._TYPES_MANIFEST_MAP[self.type]
Did you run this in Python 3? I just wanted to use the class itself here.

2018-06-05 22:35 UTC, joaquimrocha commented on tests/test_checker.py
> +            ExternalData.Type.ARCHIVE)
I don't like that this is to the left of the `=` sign. Does it fit if you bring the `self.checker...` to the line below?

2018-06-05 22:39 UTC, joaquimrocha requested changes
I like the general idea of having a lint in order to make the code coherent. For Python I think usually the code already turns out very consistent anyway, but I don't oppose to using a lint here either. It does seem a bit too harsh to enforce 80 chars in today's displays, but it's the weird formatting to accommodate the limit that I dislike. Please check my comments, and I can accept this if in the end the formatting is not completely crazy.

2018-06-05 22:40 UTC, joaquimrocha commented on src/lib/externaldata.py
> +                [checkers_folder]):
I don't like opening parenthesis without args in that line. I'd prefer to break after the `in`.

2018-06-05 22:51 UTC, ahayzen commented
@joaquimrocha Thanks for the reviews! :-) As you agree with most of the changes, other than the line length ones. How would you feel about setting the line length to, eg 100 or 120 chars ? (As this will likely solve most of the wrapping issues).

pep8 has an option to override this (as it is a debatable option), eg we could run the linting with `pep8 --max-line-length=100` (or any other length). And then we could add the linter's with their options to either a separate script or built into the run_tests script.

I'll try and go through the rest of your requests today or tomorrow :-)

2018-07-04 01:13 UTC, ahayzen commented
Hmm seems merge conflict resolutions have either caused the diff to be wrong, or the diff is confused. I'll investigate tomorrow. Don't merge for now.

2018-07-04 17:54 UTC, ahayzen commented
OK, so turns out that github is showing the diff of all the commits, instead of the diff against master - maybe i'm holding it wrong ;-)  The diff can be seen here https://github.com/joaquimrocha/flatpak-external-data-checker/compare/master...ahayzen:pep8-pyflakes

@joaquimrocha could you re-review now that max line length is 100 ?

2018-08-03 16:17 UTC, joaquimrocha commented
@ahayzen I was trying to review this today but it's no longer applying correctly to master (I know it's my fault since it took me a while to do it). However, I noticed that you call `pep8` which seems to have changed into `pycodestyle` and apparently `pyflakes3` doesn't exist in Fedora (it's `pyflakes-3`).

It seems like `flake8` is a much more powerful alternative (it uses the mentioned ones as plugins IIRC), so if you want use that instead, please open a new PR.

2018-08-03 16:17 UTC, closed without merging